apiVersion: v1
kind: PersistentVolume
metadata:
  name: datalake-pv
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.83 # NFS server IP address 
    path: "/mnt/user/datalake"   # NFS share location 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datalake-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi