---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapper
  template:
    metadata:
      labels:
        app: scrapper
    spec:
      containers:
        - name: scrapper
          image: my-scrapper:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: fluffy-system-creds
          # If you want to mount the same PVC:
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: datalake-pvc