---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapper
  template:
    metadata:
      labels:
        app: scrapper
    spec:
      containers:
        - name: scrapper
          image: my-scrapper:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin123"
            - name: BUCKET_NAME
              value: "stocks-lake"
          # If you want to mount the same PVC:
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: nfs-pvc