apiVersion: v1
kind: Pod
metadata:
  name: test-nfs
spec:
  containers:
    - name: test
      image: busybox
      command: ["sh", "-c", "id && touch /mnt/testfile && ls -l /mnt"]
      securityContext:
        runAsUser: 999
      volumeMounts:
        - name: nfs
          mountPath: /mnt
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: postgres-pvc
  restartPolicy: Never